export { Header } from "./Header";
export { Hero } from "./Hero";
export { About } from "./About";
export { Experience } from "./Experience";
export { Skills } from "./Skills";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
export { InteractiveBackground } from "./InteractiveBackground";
export { Education } from "./Education";
